### ISSUE TITLE
Map

### ISSUE THREAD

**Issue by ttching2** [PDZaninov/GoLang-Compiler#71]
**Functionality check list**
- [x] Implement map type

- [ ] Adds keys and values

- [x] Prints keys and values

- [ ] Basic map functions added

- [ ] Iterate over map

**Physical code check list**
- [ ] Make built in function

- [x] Map Type Go Node

- [x] ValueSpec IR node

- [x] Map Type IR node

- [x] Update Go IR visitor, visitor

- [ ] Update Truffle

- [x] Update Parser

- [x] Index Expression (?) Guessing already done for arrays.

- [x] Update Go types

- [ ] Go Read and Write variables

**Comment by iinno** [comment]
- var m map[string]int -> declaring a variable m, HOWEVER, m is a reference and until you call the built-in function **make** which allocates and initializes the hash map. m until make is called returns nill and attempting to read will behave like its empty but writing to it will cause a run-time error. 

-In order to implement this in java, since we do not have pointers translated yet, I will initially assign a empty java hash map (somehow not allowing write to it)/ or just have it be nil (have to look into how java reacts when trying read/write to nil), then when make is called, assign a new hash map (garbage collection will get rid of the unused one I'm guessing).

**Comment by iinno** [comment]
[Untitled Diagram.pdf](https://github.com/PDZaninov/GoLang-Compiler/files/1814428/Untitled.Diagram.pdf)

**Comment by iinno** [comment]
![untitled diagram](https://user-images.githubusercontent.com/17774953/37450775-91d8e796-27ec-11e8-925e-71f61c93ee16.jpg)

**Comment by iinno** [comment]
NOTE: Dont forget to add imports of maptype ir and truffle to visitor, truffle, parser

**Comment by iinno** [comment]
- Gowritelocal variable lines 49, 152: made copies of the slices and array code segment.
